package Exception;

public class ExceptionHandling {
    public static void main(String[] args) {
        // try{
        //     int data=100/0;
        // }
        // catch(ArithmeticException e)
        // {System.out.println(e);}

        // Arrayoutofbound
        // try{
        //     int[] number={1,3,5};
        //     System.out.println(number[10]);
        // }
        // catch (Exception e){
        //     System.out.println("Bad Code");

        // }finally{
        //     System.out.println("try catch finished");
        // }
        
    }
    
}
